name: Convert All JSON Files to SRS

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'

jobs:
  convert-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: 设置 Git 用户信息
      - name: Set up Git user
        run: |
          git config --global user.name "Rictusempra666"
          git config --global user.email "tcmickeyzhou@gmail.com"

      # Step 3: 安装 sing-box
      - name: Install sing-box
        run: |
          curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.29/sing-box-1.10.0-alpha.29-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          chmod +x sing-box-1.10.0-alpha.29-linux-amd64/sing-box
          sudo mv sing-box-1.10.0-alpha.29-linux-amd64/sing-box /usr/local/bin/sing-box
          sing-box version

      # Step 4: 删除旧的 SRS 文件
      - name: Remove old SRS files
        run: |
          echo "Removing old .srs files..."
          find . -type f -name "*.srs" -exec rm -f {} \;

      # Step 5: 转换 JSON 文件为 SRS 文件
      - name: Convert JSON Files to SRS
        run: |
          json_files=$(find . -type f -name "*.json")
          if [ -z "$json_files" ]; then
            echo "No JSON files to convert."
            exit 0
          fi
          for json_file in $json_files; do
            output_file="${json_file%.json}.srs"
            echo "Converting $json_file to $output_file..."
            if ! sing-box rule-set compile --output "$output_file" "$json_file"; then
              echo "Error compiling $json_file"
              exit 1
            fi
          done

      # Step 6: 提交生成的 SRS 文件
      - name: Commit and Push SRS Files
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-converted SRS files from JSON"
            git push
