name: Convert All JSON Files to SRS

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'

jobs:
  convert-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: 设置 Git 用户信息
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: 安装 sing-box
      - name: Install sing-box
        run: |
          curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.29/sing-box-1.10.0-alpha.29-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          chmod +x sing-box-1.10.0-alpha.29-linux-amd64/sing-box
          sudo mv sing-box-1.10.0-alpha.29-linux-amd64/sing-box /usr/local/bin/sing-box

      # Step 4: 验证 sing-box 安装
      - name: Verify Sing-box Installation
        run: sing-box version

      # Step 5: 转换 JSON 文件为 SRS 文件
      - name: Convert JSON Files to SRS
        run: |
          json_files=$(find . -type f -name "*.json")
          for json_file in $json_files; do
            output_file="${json_file%.json}.srs"
            sing-box rule-set compile --output "$output_file" "$json_file"
          done

      # Step 6: 提交生成的 SRS 文件
      - name: Commit and Push SRS Files
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-converted SRS files from JSON"
            git push
          fi
